### ISSUE TITLE
Second Stage Ideas

### ISSUE THREAD

**Issue by Rud156** [Rud156/A-Bad-Day#1]
### Post Ideas for Second Stage Here:

- [ ] Add a fly in camera initially
- [x] Add a cave exploration part
- [x] Add a sunset
- [x] Add platform moving puzzles similar to first scene
- [x] Change Environemt
- [x] Keep same theme as first scene

**Comment by Devashish0312** [comment]
Change the environment

**Comment by Devashish0312** [comment]
Maintain the same theme as of Floating cubes, fog and mist.
